version: 2.1
# These environment variables must be set in CircleCI UI
#
# DOCKER_EMAIL   - login info for docker hub
# DOCKER_USER
# DOCKER_PASS
#
orbs:
  cloudfoundry: circleci/cloudfoundry@0.1.73
jobs:
  build:
    docker:
      - image: cimg/openjdk:14.0
    working_directory: ~/securing-devops
    steps:
      - checkout
      - restore_cache:
          key: securing-devops-boot-{{ checksum "pom.xml" }}
      - run: ./mvnw dependency:resolve dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: securing-devops-boot-{{ checksum "pom.xml" }}
      - run: ./mvnw -o clean verify
      - store_test_results:
          path: ~/junit
      - store_artifacts: 
          path: target/invoicer-0.0.1-SNAPSHOT.jar
      - store_artifacts:
          path: src/main/resources/invoicer-manifest.yml
      - run:
          name: Copy deployment artifacts to workspace
          command: |
            cp target/invoicer-*.jar /tmp/invoicer.jar
            cp src/main/resources/invoicer-manifest.yml /tmp/
      - persist_to_workspace:
          root: /tmp
          paths:
            - invoicer.jar
            - invoicer-manifest.yml

  spot_bugs:
    docker:
      - image: cimg/openjdk:14.0
    steps:
      - checkout
      - restore_cache:
          key: securing-devops-boot-{{ checksum "pom.xml" }}

      - run: ./mvnw -o verify spotbugs:check -DskipTests

  dependency_check:
    docker:
      - image: cimg/openjdk:14.0
    steps:
      - checkout
      - restore_cache:
          key: securing-devops-boot-{{ checksum "pom.xml" }}

      - run: ./mvnw dependency-check:check

  zap_baseline_scan:
    docker:
      - image: cimg/openjdk:14.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.12
      - run: |
          # Create container holding the configuration
          docker create -v /zap/wrk --name zapwrk alpine:3.4 /bin/true
          # Copy zap-baseline.conf to volumne
          docker cp ./zap-baseline.conf zapwrk:/zap/wrk
      - run:
          command: |
            (
              docker pull owasp/zap2docker-weekly && \
              docker run \
                --volumes-from zapwrk \
                -t owasp/zap2docker-weekly zap-baseline.py -d -c zap-baseline.conf -t https://invoicer.cfapps.io || \
              if [ $? -ne 1 ]; then exit 0; else exit 1; fi;
            )
  tlsobs:
    docker:
      - image: cimg/go:1.14
    steps:
      - run: |
          go get github.com/mozilla/tls-observatory/tlsobs
          tlsobs invoicer.cfapps.io

workflows:
  version: 2
  default:
    jobs:
      - build
      - cloudfoundry/push:
          requires: 
            - build
          workspace_path: /tmp
          appname: invoicer
          org: Conspect
          space: development
          manifest: /tmp/invoicer-manifest.yml
          package: /tmp/invoicer.jar
      - dependency_check:
          requires:
            - build
      - spot_bugs:
          requires:
            - build
      - zap_baseline_scan:
          requires:
            - cloudfoundry/push
      - tlsobs:
          requires:
            - cloudfoundry/push
