CREATE SEQUENCE hibernate_sequence START WITH 1 INCREMENT BY 1;

CREATE TABLE charge (id BIGINT GENERATED BY DEFAULT AS IDENTITY, amount DECIMAL(19,2), description VARCHAR(255), type varchar(255), invoice_id bigint, primary key (id));
CREATE TABLE invoice (id BIGINT GENERATED BY DEFAULT AS IDENTITY, amount DECIMAL(19,2), due_date DATE, paid BOOLEAN NOT NULL, payment_date DATE, PRIMARY KEY (id));

ALTER TABLE charge ADD CONSTRAINT FK_CHARGE_INVOICE FOREIGN KEY (invoice_id) REFERENCES invoice;

INSERT INTO invoice (amount, due_date, paid) VALUES (1000, '2020-10-10', false);
INSERT INTO invoice (amount, due_date, paid) VALUES (2000, '2020-10-12', false);